config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about' => 'pages#about'

  resources :articles

  get 'signup' => 'users#new'
  #post 'users' => 'users#create'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save {self.email = email.downcase}
  validates :username,
    presence: true,
    uniqueness: {case_sensitive: false},
    length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
    presence: true,
    length: {maximum: 105},
    uniqueness: {case_sensitive: false},
    format: {with: VALID_EMAIL_REGEX}

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def edit

  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update

    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show

  end

  def destroy

    @article.destroy
    flash[:danger] = "Article was successfully deleted."
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:danger] = "You can only edit or delete your own article"
        redirect_to root_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "Login incorrect"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the application #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 1)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles crated by user have been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  def set_user
    @user = User.find(params[:id])
  end
  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end
  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Only admin cad do that"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle img-fluid")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8">
      <div class="card">
        <div class="card-header">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="card-body">
          <small>
              Created by: <%= article.user.username if article.user %>,
              <%= time_ago_in_words(article.created_at) %> ago,
              last update: <%= time_ago_in_words(article.updated_at) %>
          </small>
          <p class="card-text">
            <%= truncate(article.description, length: 100) %>
          <p>

          <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(article), method: :delete,
              data: {confirm: "Are you sure?"},
              class: "btn btn-xs btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-10">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-10">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>

    <div class="col-xs-4 cols-xs-offset-4">
      <%= link_to "Back to articles listing", articles_path %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'shared/page_header', title: "Edit existing article" %>

<div class="main main-raised">
  <div class="section section-basic">
    <div class="container">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<%= render 'shared/page_header', title: "Listing all articles" %>

<div class="main main-raised">
  <div class="section section-basic">
    <div class="container">
      <%= render 'article', obj: @articles %>

      <div align="center">
        <%= will_paginate %>
      </div>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'shared/page_header', title: "Create an article" %>

<div class="main main-raised">
  <div class="section section-basic">
    <div class="container">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<%= render 'shared/page_header', title: @article.title %>

<div class="main main-raised">
  <div class="section section-basic">
    <div class="container">
      <div class="center">
        Description
      </div>
      <hr/>
      <%= simple_format(@article.description) %>


      <div class="article-actions">
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete this article", article_path(@article), method: :delete,
              data: {confirm: "Are you sure?"},
              class: "btn btn-xs btn-danger" %>
        <% end %>``
        <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer" data-background-color="black">
  <div class="container">
    <nav class="float-left">
      <ul>
        <li><%= link_to "About", about_path, class: "text-muted"%></li>
      </ul>
    </nav>

    <div class="copyright float-right">
      Copyright &copy <a href="#">link</a> by somebody
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% if !flash.empty? %>
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= "#{name}" %>">
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-color-on-scroll fixed-top navbar-expand-lg">
  <div class="container">
    <div class="navbar-translate">
      <%= link_to "Tenwords", root_path, class: "navbar-brand", id:"logo" %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'Log out', logout_path, method: :delete, class: "nav-link p-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Articles", articles_path, class: "nav-link p-2" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-item nav-link dropdown-toggle mr-md-2" href="#" id="bd-versions" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Action
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="bd-versions">
              <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class: "nav-link p-2" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', signup_path, class: "nav-link p-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tenwords</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="index-page sidebar-collapse">
    <%= render 'layouts/navigation' %>

    <%= yield %>

    <%= render 'layouts/messages' %>
    <%= render 'layouts/footer' %>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<%= render 'shared/page_header', title: "About" %>

<div class="main main-raised">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <h3><%= link_to 'Home', root_path %></h3>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/page_header', title: "Home", subtitle: "Some text" %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="card card-nav-tabs">
  <div class="card-header card-header-danger">
          <%= pluralize(obj.errors.count, "error") %>
          prohibited this article from being saved:
  </div>
  <ul class="list-group list-group-flush">
    <% obj.errors.full_messages.each do |msg| %>
      <li class="list-group-item"><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_page_header.html.erb
<div class="page-header header-filter clear-filter purple-filter" data-parallax="true"
    style="height: 300px; background-image: url(&quot;https://demos.creative-tim.com/material-kit/assets/img/bg2.jpg&quot;); transform: translate3d(0px, 15px, 0px); ">
  <div class="container">
    <div class="row">
      <div class="col-md-8 ml-auto mr-auto">
        <div class="brand">
          <h1><%= title %></h1>
          <h3><%= subtitle if defined?(subtitle) %></h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="main main-raised">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-10">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-10">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-10">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-10">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update your account", class: "btn btn-primary btn-lg") %>
        </div>
      </div>
    <% end %>

    <div class="col-xs-4 cols-xs-offset-4">
      <%= link_to "Back to articles listing", articles_path %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'shared/page_header', title: "Edit your account" %>

<%= render 'form' %>

app/views/users/index.html.erb
<%= render 'shared/page_header', title: "All users" %>

<div class="main main-raised">
  <div class="section section-basic">
    <% @users.each do |user| %>
          <div class="card">
            <div class="card-body">
              <li>
                <%= link_to gravatar_for(user), user_path(user) %>
              </li>
              <li>
                <%= link_to user.username, user_path(user) %>
              </li>
              <li>
                <small>
                  <%= pluralize(user.articles.count, 'article') %>
                </small>
              </li>
              <% if logged_in? && current_user.admin? %>
              <li>
                  <%= link_to "Delete this user", user_path(user), method: :delete,
                    data: {confirm: "Are you sure you want to destroy the user and his articles?"} %>
              </li>
              <% end %>
            </div>
          </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'shared/page_header', title: "Signup" %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/page_header', title: "Welcome to #{@user.username}'s page" %>

<div class="main main-raised">
  <div class="col-md-5 p-lg-5 mx-auto my-5">
    <p align="center">
      <%= gravatar_for @user, size: 150 %>
    </p>

    <h4 align="center">
      <%= @user.username %>'s articles
    </h4>

    <div class="center">
      <%= will_paginate @user_articles %>
    </div>
    <%= render 'articles/article', obj: @user_articles  %>

  </div>
</div>